openapi: 3.1.0

info:
  title: AI裁判官
  summary: AIが補助してゲームみたいに楽しく揉め事を解決するWebアプリのAPI
  version: 1.0.1

paths:
  /trial/create/:
    post:
      tags: [Trial]
      summary: 裁判を作成する
      description: |
        プロジェクター用 <br>
        裁判を作成する.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrialCreate'
      responses:
        '201':
          description: 裁判作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialCreateResponse'

  /trial/claims_and_judgments/:
    post:
      tags: [Trial]
      summary: 主張または判決を取得する
      description: |
        プロジェクター用 <br>
        - 原告の主張 (plaintiff_claim),
        - 被告の主張 (defendant_claim),
        - 裁判官の暫定的な判決 (judge_judgment),
        - 原告の最終主張 (plaintiff_final_claim),
        - 被告の最終主張 (defendant_final_claim),
        - 裁判官の最終判決 (judge_final_judgment)
        を取得するエンドポイント.<br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimsAndJudgments'
      responses:
        '200':
          description: 主張または判決取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimsAndJudgmentsResponse'
  /trial/game_state/:
    post:
      tags: [Trial]
      summary: ゲームの初期進行状態を取得する
      description: |
        プロジェクター，スマホ用 <br>
        ゲームの初期進行状態を取得するエンドポイント。<br>
        - 2つのQRコードを表示するフェーズ (show_two_qr_codes),
        - 1つのQRコードを表示するフェーズ (show_one_qr_codes), 
        - 原告の主張，被告の主張，裁判官の暫定的な判決を表示するフェーズ (show_first_claim_and_judge),
        - 話し合いのフェーズ (discussion)
        - 最後の主張と判決を表示するフェーズ (show_final_claim_and_judge)
        を指示する．
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrialGameState'
      responses:
        '200':
          description: ゲームの初期進行状態取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialGameStateResponse'

  /trial/game_state/set/:
    post:
      tags: [Trial]
      summary: ゲームの進行状態を設定する
      description: |
        プロジェクター用 <br>
        ゲームの進行状態をバックエンドを伝えるエンドポイント.<br>
        以下のタイミングで叩くことを想定している.<br>
        - 裁判官の暫定的な判決を表示が終わったタイミング (discussion) <br>
        - 話し合いが終了したタイミング (show_final_claim_and_judge) <br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrialGameStateSet'
      responses:
        '200':
          description: ゲームの進行状態設定成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialGameStateSetResponse'


  /trial/player/create/:
    post:
      tags: [Trial]
      summary: 裁判に参加するプレイヤーの名前を登録する
      description: |
        スマホ用 <br>
        QRコードを読み取り、名前を登録するエンドポイント<br>
        ロールは、plaintiff (原告), defendant (被告), spectator (傍聴人)のいずれか<br>
        main_chat_id: 原告，被告，裁判官の3者が話すのチャットのID<br>
        sub_chat_id: 傍聴人が話すチャットのID (傍聴人のプレイヤーの名前登録時には値が存在) <br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerCreate'
      responses:
        '201':
          description: プレイヤー作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerCreateResponse'
  /trial/claim/:
    post:
      tags: [Trial]
      summary: 主張を作成する
      description: |
        スマホ用 <br>
        原告、被告がQRコードを読み取り、名前を入力した後、最初の主張で入力した内容をPOSTするエンドポイント.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimCreate'
      responses:
        '201':
          description: 主張作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimCreateResponse'
    patch:
      tags: [Trial]
      summary: 主張を更新する
      description: |
        スマホ用 <br>
        裁判内容に対する主張を更新するエンドポイント。<br>
        ゲーム開始後は、原告、被告が主張を更新することができ、その時はこのPATCHを叩いて更新する.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClaimUpdate'
      responses:
        '200':
          description: 主張更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimUpdateResponse'
  /chat/{chat_id}/message/polling/:
    get:
      tags: [Chat]
      summary: チャット内の新規メッセージを取得する
      description: |
        クライアントは、チャットのIDとリクエスト時点で保持している最新メッセージのcreated_atを用いて、定期的にこのエンドポイントを呼び出し、新しいメッセージを取得する。<br>
        レスポンスの配列内のメッセージは、created_atが古いのが先頭になるように並べられる。
      parameters:
        - in: path
          name: chat_id
          required: true
          description: 
          schema:
            $ref: '#/components/schemas/id'
        - in: query
          name: latest_message_created_at
          required: true
          description: 
          schema:
            $ref: '#/components/schemas/created_at'
      responses:
        '200':
          description: メッセージ取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatGetResponse'      
  /chat/latest_message/:
    post:
      tags: [Chat]
      summary: メインチャット内の最新メッセージを取得する
      description: | 
        議論フェーズでは、プロジェクターに（原告、被告、裁判官の3者が話しているメインの）チャットの最新メッセージを表示する。<br>
        その際に必要な最新メッセージを取得するためのエンドポイント。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LatestChatMessage'
      responses:
        '200':
          description: メッセージ取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LatestChatMessageResponse'
  /message/create/:
    post:
      tags: [Chat]
      summary: チャットにメッセージを送信する
      description: |
        クライアントは、チャットIDと発信者IDと発言内容をリクエストする。<br>
        サーバーは、メッセージを保存し、AIを呼び出す。<br>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreateRequset'
      responses:
        '201':
          description: メッセージ送信成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /message/{message_id}/good/:
    post:
      tags: [Chat]
      summary: メッセージにグッドをつける
      parameters:
        - in: path
          name: message_id
          required: true
          description: 対象のメッセージID
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageReactionRequest'
      responses:
        '200':
          description: メッセージグッド成功
          content:
            application/json:
              example:
                success: "グッドをつけました。"
  /message/{message_id}/ungood/:
    post:
      tags: [Chat]
      summary: メッセージのグッドを取り消す
      parameters:
        - in: path
          name: message_id
          required: true
          description: 対象のメッセージID
          schema:
            $ref: '#/components/schemas/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageReactionRequest'
      responses:
        '200':
          description: メッセージに対するリアクション(グッド)の取り消し成功
          content:
            application/json:
              example:
                success: "グッドを取り消しました。"


components:
  schemas:
    # 要素一つ一つの定義 ABC順
    claim:
      type: string
      maximum: 100
      examples:
        - "お腹が空いていたとしても人のプリンを食べるのは重罪"

    created_at:
      type: string
      examples:
        - "2024-09-16T10:35:49.716241+09:00"

    game_state:
      type: string
      enum: [show_two_qr_codes, show_one_qr_codes, show_first_claim_and_judge, discussion, show_final_claim_and_judge]
      examples:
        - discussion

    id:
      type: string
      format: uuid
      examples:
        - 123e4567-e89b-12d3-a456-426614174000

    message:
      type: string
      maximum: 100
      examples:
        - "Aさんの主張についてコメントします。プリンの容器の底の名前なんて見えません。"

    player_name:
      type: string
      examples:
        - "Player1"

    resource:
      type: string
      examples:
        - "お腹が空いていたとしても人のプリンを食べるのは重罪のため、原告に賠償金を支払うように判決します。"
    
    resource_type:
      type: string
      enum: [plaintiff_claim, defendant_claim, provisional_judgment, plaintiff_final_claim, defendant_final_claim, final_judgment]
      examples:
        - judge_judgment

    role:
      type: string
      enum: [plaintiff, defendant, spectator, judge]
      examples:
        - plaintiff

    trial_subject:
      type: string
      maximum: 50
      examples:
        - "プリンを食べたことについて"

    # リクエスト・レスポンスの定義 ABC順
    ChatGetResponse:
      type: array
      items:
        type: object
        properties:
          message_id:
            $ref: '#/components/schemas/id'
          chat_id:
            $ref: '#/components/schemas/id'
          player_id:
            $ref: '#/components/schemas/id'
          player_name:
            $ref: '#/components/schemas/player_name'
          player_role:
            $ref: '#/components/schemas/role'
          message:
            $ref: '#/components/schemas/message'
          created_at:
            $ref: '#/components/schemas/created_at'

    ClaimCreate:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        claim:
          $ref: '#/components/schemas/claim'
      required:
        - trial_id
        - player_id
        - claim
  
    ClaimCreateResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        claim:
          $ref: '#/components/schemas/claim'

    ClaimsAndJudgments:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        resource_type:
          $ref: '#/components/schemas/resource_type'

    ClaimsAndJudgmentsResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        resource_type:
          $ref: '#/components/schemas/resource_type'
        resource:
          $ref: '#/components/schemas/resource'




    ClaimUpdate:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        claim:
          $ref: '#/components/schemas/claim'
      required:
        - trial_id
        - player_id
        - claim
      
    ClaimUpdateResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        claim:
          $ref: '#/components/schemas/claim'

    LatestChatMessage:
      type: object
      properties:
        chat_id:
          $ref: '#/components/schemas/id'
      required:
        - chat_id

    LatestChatMessageResponse:
      type: object
      properties:
        chat_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        player_name:
          $ref: '#/components/schemas/player_name'
        message_id:
          $ref: '#/components/schemas/id'
        message:
          $ref: '#/components/schemas/message'
        created_at:
          $ref: '#/components/schemas/created_at'

    MessageCreateRequset:
      type: object
      properties:
        chat_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        message:
          $ref: '#/components/schemas/message'

    MessageReactionRequest:
      type: object
      properties:
        player_id:
          $ref: '#/components/schemas/id'

    MessageResponse:
      type: object
      properties:
        message_id:
          $ref: '#/components/schemas/id'
        chat_id:
          $ref: '#/components/schemas/id'
        player_id:
          $ref: '#/components/schemas/id'
        player_name:
          $ref: '#/components/schemas/player_name'
        message:
          $ref: '#/components/schemas/message'
        created_at:
          $ref: '#/components/schemas/created_at'

    PlayerCreate:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        role:
          $ref: '#/components/schemas/role'
        player_name:
          $ref: '#/components/schemas/player_name'
      required:
        - trial_id
        - role
        - player_name

    PlayerCreateResponse:
      type: object
      properties:
        player_id:
          $ref: '#/components/schemas/id'
        player_name:
          $ref: '#/components/schemas/player_name'
        role:
          $ref: '#/components/schemas/role'
        main_chat_id:
          $ref: '#/components/schemas/id'
        sub_chat_id:
          $ref: '#/components/schemas/id'

    TrialCreate:
      type: object
      properties:
        subject:
          $ref: '#/components/schemas/trial_subject'
      required:
        - subject

    TrialCreateResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        subject:
          $ref: '#/components/schemas/trial_subject'
        created_at:
          $ref: '#/components/schemas/created_at'

    TrialGameState:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
    
    TrialGameStateResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        game_state:
          $ref: '#/components/schemas/game_state'

    TrialGameStateSet:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        game_state:
          $ref: '#/components/schemas/game_state'

    TrialGameStateSetResponse:
      type: object
      properties:
        trial_id:
          $ref: '#/components/schemas/id'
        game_state:
          $ref: '#/components/schemas/game_state'
