# Generated by Django 4.2.16 on 2024-10-21 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50, verbose_name='裁判内容')),
                ('plaintiff_claim', models.CharField(max_length=100, verbose_name='原告の主張')),
                ('plaintiff_final_claim', models.CharField(max_length=100, verbose_name='原告の最終主張')),
                ('defendant_claim', models.CharField(max_length=100, verbose_name='被告の主張')),
                ('defendant_final_claim', models.CharField(max_length=100, verbose_name='被告の最終主張')),
                ('provisional_judgment', models.CharField(max_length=100, verbose_name='暫定的な判決')),
                ('final_judgment', models.CharField(max_length=100, verbose_name='最終判決')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '裁判',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('role', models.CharField(choices=[('plaintiff', '原告'), ('defendant', '被告'), ('judge', '裁判官'), ('spectator', '傍聴人')], max_length=10, verbose_name='役職')),
                ('trial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.trial', verbose_name='裁判')),
            ],
            options={
                'verbose_name': 'プレイヤー',
            },
        ),
    ]
