# Generated by Django 4.2.16 on 2024-10-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('plaintiff', '原告(A)'), ('defendant', '被告(B)'), ('judge', '裁判官'), ('spectator', '傍聴人')], max_length=10, verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='defendant_claim',
            field=models.CharField(max_length=100, verbose_name='被告(B)の主張'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='defendant_final_claim',
            field=models.CharField(max_length=100, verbose_name='被告(B)の最終主張'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='plaintiff_claim',
            field=models.CharField(max_length=100, verbose_name='原告(A)の主張'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='plaintiff_final_claim',
            field=models.CharField(max_length=100, verbose_name='原告(A)の最終主張'),
        ),
    ]
