# Generated by Django 4.2.16 on 2024-10-23 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0003_rename_trial_id_player_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('show_two_qr_codes', 'QRコードを2つ表示'), ('show_one_qr_codes', 'QRコードを1つ表示'), ('show_first_claim_and_judge', '原告の主張，被告の主張，裁判官の暫定的な判決を表示'), ('discussion', '話し合い'), ('show_final_claim_and_judge', '最終主張と判決を表示')], max_length=30, verbose_name='ゲーム状態')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.trial', verbose_name='裁判')),
            ],
        ),
    ]
