# Generated by Django 4.2.16 on 2024-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_gamestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='state',
            field=models.CharField(choices=[('show_two_qr_codes', 'QRコードを2つ表示'), ('show_one_qr_codes', 'QRコードを1つ表示'), ('show_first_claim_and_judge', '原告の主張,被告の主張,裁判官の暫定的な判決を表示'), ('discussion', '話し合い'), ('show_final_claim_and_judge', '最終主張と判決を表示')], max_length=30, verbose_name='ゲーム状態'),
        ),
    ]
