# Generated by Django 4.2.16 on 2024-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0005_alter_gamestate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='discussion_content',
            field=models.TextField(default='', max_length=100, verbose_name='話し合い内容'),
        ),
    ]
