# Generated by Django 4.2.16 on 2024-10-21 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('isMain', models.BooleanField(default=False, verbose_name='メインチャットかどうか')),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.trial', verbose_name='裁判')),
            ],
            options={
                'verbose_name': 'チャット',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100, verbose_name='発言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.chat', verbose_name='チャット')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.player', verbose_name='発言者')),
            ],
            options={
                'verbose_name': 'メッセージ',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, primary_key=True, serialize=False)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message', verbose_name='メッセージ')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trials.player', verbose_name='グッドを押したプレイヤー')),
            ],
            options={
                'verbose_name': 'グッド',
            },
        ),
    ]
