# Generated by Django 4.2.16 on 2024-10-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_id_alter_good_id_alter_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='isMain',
            new_name='is_main',
        ),
    ]
