# Generated by Django 4.2.16 on 2024-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_ismain_chat_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='trail_id',
            new_name='trail',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='player_id',
            new_name='player',
        ),
    ]
