# Generated by Django 4.2.16 on 2024-10-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rename_trail_id_chat_trail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='trail',
            new_name='trial',
        ),
    ]
