# Generated by Django 4.2.16 on 2024-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_rename_trail_chat_trial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='good',
            constraint=models.UniqueConstraint(fields=('message', 'player'), name='unique_good'),
        ),
    ]
